apiVersion: v1
kind: Namespace
metadata:
  name: hello-docker-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-http
  namespace: hello-docker-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-http
  template:
    metadata:
      labels:
        app: hello-http
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      containers:
        - name: http
          image: python:3.12-slim@sha256:2c941e860699f878900b0edc2403613c234d4b32eda3cc9fa7036991a2a63c4a
          command: ["python", "-m", "http.server", "8080"]
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-http
  namespace: hello-docker-lab
spec:
  selector:
    app: hello-http
  ports:
    - port: 80
      targetPort: 8080
